drug_keywords = [
    r'\bibogaine\b', r'\bibo\b', r'\bthe visionary root\b',
    r'\bmethylone\b', r'\bm1\b', r'\bexplosion\b', r'\bm-kat\b',
    r'\bdesomorphine\b', r'\bkrokodil\b', r'\bcroc\b', r'\bzombie drug\b',
    r'\bdiphenhydramine\b', r'\bdph\b', r'\bpinkies\b', r'\bbenadryl\b',
    r'\bhydromorphone\b', r'\bdilaudid\b', r'\bdust\b', r'\bjuice\b',
    r'\b25i-nbome\b', r'\bn-bomb\b', r'\bsmiles\b', r'\b25i\b',
    r'\bmdma \b',r'\bmethylone\b', r'\bm1\b', r'\bmolly\b', r'\becstasy\b',
    r'\b4-methylmethcathinone\b',r'\bmephedrone\b', r'\bdrone\b', r'\bmeow meow\b', r'\bbubbles\b',
    r'\bpentedrone\b', r'\bpento\b', r'\bα-pvp\b', r'\bgravel\b',
    r'\bpara-methoxyamphetamine\b', r'\bpma\b', r'\bpink ecstasy\b', r'\bchicken yellow\b', r'\bdeath\b',
    r'\b2c-b\b', r'\bnexus\b', r'\bbromo\b', r'\bvenus\b',
    r'\b2c-i\b', r'\bsmiles\b', r'\bpink champagne\b',
    r'\bbenzylpiperazine \bzp\b', r'\ba2\b', r'\bpep pills\b', r'\bfrenzy\b',
    r'\bdoxylamine\b', r'\bdxm\b', r'\btriple c\b', r'\brobo\b',
    r'\b5-meo-dmt\b', r'\bthe god molecule\b', r'\btoad\b', r'\bbufo\b',
    r'\bkratom\b', r'\bthang\b', r'\bkakuam\b', r'\bthom\b', r'\bketum\b',
    r'\bamt\b', r'\balpha-methyltryptamine\b', r'\bspirals\b', r'\balpha\b',
    r'\bmethaqualone\b', r'\bludes\b', r'\bmandrax\b', r'\bbuttons\b',
    r'\bamyl nitrate\b', r'\bpoppers\b', r'\bsnappers\b', r'\brush\b',
    r'\b4-fluoroamphetamine\b', r'\b4-fa\b', r'\bflux\b', r'\b4-fmp\b', r'\bpal-303\b',
    r'\btryptamines\b', r'\bdpt\b', r'\bdipt\b', r'\bthe light\b', r'\bfoxy\b',
    r'\bmdpv\b', r'\bmethylenedioxypyrovalerone\b', r'\bbath salts\b', r'\bcannibal\b',
    r'\bacetylfentanyl\b', r'\bfake heroin\b', r'\bfent\b', r'\bdrop dead\b',
    r'\bbenzodiazepines\b', r'\bbenzos\b', r'\bdowners\b', r'\bzanies\b',
    r'\balpha-php\b', r'\bflakka\b', r'\bgravel\b', r'\bzombie dust\b',
    r'\bphenazepam\b', r'\bbonsai\b', r'\blegal valium\b',
    r'\b3-mmc\b', r'\b3-methylmethcathinone\b', r'\b3-m\b', r'\bmethcat\b',
    r'\bcathinone\b', r'\bkhat\b', r'\bkhat\b', r'\babyssinian tea\b', r'\btohai\b',
    r'\betizolam\b', r'\betizzy\b', r'\betilaam\b',
    r'\bchloroform\b', r'\btrichloromethane\b', r'\bknockout drops\b',
    r'\bflunitrazepam\b', r'\broofies\b', r'\bmexican valium\b', r'\bforget-me-pill\b',
    r'\bcarisoprodol\b', r'\bsoma\b', r'\bds\b', r'\bdanes\b',
    r'\bcyclobenzaprine\b', r'\bflexeril\b', r'\bcyclo\b', r'\bbenz\b',
    r'\bzolpidem\b', r'\bambien\b', r'\bzombie pills\b',
    r'\bcarfentanil\b', r'\bserial killer\b', r'\bdrop dead\b', r'\belephant tranquilizer\b',
    r'\btapentadol\b', r'\bnucynta\b', r'\bpainkillers\b',
    r'\bgamma-butyrolactone\b', r'\bgbl\b', r'\bg\b', r'\bliquid x\b', r'\bfish tank cleaner\b',
    r'\boxycontin\b', r'\bocs\b', r'\boxy\b', r'\bhillbilly heroin\b',
    r'\b2c-e\b', r'\beuropa\b', r'\bspace trips\b',
    r'\bbutyl nitrite\b', r'\brush\b', r'\bliquid gold\b',
    r'\bcatha edulis\b', r'\bkhat\b', r'\bkhat\b', r'\bafrican salad\b', r'\babyssinian tea\b',
    r'\bclonazolam\b', r'\bclonitrazolam\b', r'\bclam\b', r'\bclz\b',
    r'\bcyclopropylfentanyl\b', r'\bcyclo-fent\b', r'\bcyclone\b',
    r'\bgabapentin\b', r'\bgabbies\b', r'\bmorontin\b',
    r'\bpregabalin\b', r'\blyrica\b', r'\bbudweisers\b',
    r'\bfuranylfentanyl\b', r'\bfenty\b', r'\bfentanyl\b',
    r'\bthiopental\b', r'\bpentothal\b', r'\btruth serum\b',
    r'\bmdpbp\b', r'\bbath salts\b', r'\bdrone\b',
    r'\beutylone\b', r'\bbooty\b', r'\byellow brick\b',
    r'\b2c-c\b', r'\bmagic c\b', r'\btripstacy\b',
    r'\bdesoxypipradrol\b', r'\b2-dpmp\b', r'\bivory wave\b', r'\bbath salts\b', r'\bocean burst\b',
    r'\bisotonitazene\b', r'\biso\b', r'\btony\b',
    r'\bu-47700\b', r'\bpink\b', r'\bu4\b',
    r'\bα-methylfentanyl\b', r'\bchina white\b', r'\bwhite persian\b',
    r'\bw-18\b', r'\bsynthetic heroin\b', r'\bsuper heroin\b',
    r'\bn-ethylpentylone\b', r'\bn-ethyl\b', r'\bmonkey dust\b',
    r'\bflubromazolam\b', r'\bflub\b', r'\bflubrom\b',
    r'\bthiopental sodium\b', r'\bpentothal\b', r'\btruth serum\b',
    r'\betorphine\b', r'\bimmobilon\b', r'\belephant juice\b',
    r'\bgbl\b' ,r'\bgamma-butyrolactone\b', r'\bg\b', r'\bfish cleaner\b', r'\bliquid x\b',
    r'\bmethoxetamine\b', r'\bmxe\b', r'\bmexxy\b', r'\bk-mass\b',
    r'\b3-fpm\b', r'\b3-f\b', r'\bflake\b', r'\bspeed\b',
    r'\bfub-amb \synthetic cannabinoid\\b', r'\bnoids\b', r'\bk2\b', r'\bspice\b',
    r'\ba-pvp\b', r'\bflakka\b', r'\bgravel\b',
    r'\bdiclazepam\b', r'\bdiclaz\b', r'\blegal xanax\b',
    r'\bα-php\b', r'\balpha\b', r'\bzombie\b',
    r'\b2c-t-7\b', r'\bblue mystic\b', r'\btweety bird\b',
    r'\bmethoxphenidine\b', r'\bmxp\b', r'\bnoxies\b',
    r'\b4-fa\b', r'\b4-fluoroamphetamine\b', r'\bflux\b', r'\b4-fmp\b', r'\bf\b',
    r'\b5f-adb\b', r'\bsynthetic cannabinoid\b', r'\bfake weed\b', r'\bspice\b', r'\bk2\b',
    r'\bflunitrazepam\b', r'\brohypnol\b', r'\broofies\b',
    r'\bmirtazapine\b', r'\bmirt\b', r'\bzispin\b', r'\bremaron\b',
    r'\b4-cmc\b', r'\bclefedrone\b', r'\b4-chloromethcathinone\b',
    r'\balpha-ethyltryptamine\b', r'\baet\b', r'\be.t.\b', r'\bα-et\b',
    r'\b25b-nbome\b', r'\bn-bomb\b', r'\b25b\b',
    r'\bSnow\b', r'\bBlow\b', r'\bCoke\b', r'\bYayo\b', r'\bNose Candy\b',
    r'\bFlake\b', r'\bDust\b', r'\bBase\b', r'\bCrack\b', r'\bRock\b',
    r'\bWhite\b', r'\bPowder\b', r'\bFishscale\b', r'\bCharlie\b',
    r'\bWhite Lady\b', r'\bLady\b', r'\bPerico\b', r'\bSpeedball\b',
    r'\bBump\b', r'\bLine\b', r'\bEightball\b', r'\bSnow White\b',
    r'\bSnowstorm\b', r'\bPearl\b', r'\bWhite Girl\b', r'\bBooger Sugar\b',
    r'\bSoft\b', r'\bSniff\b', r'\bToot\b', r'\bBlanca\b', r'\bBig C\b',
    r'\bCandy\b', r'\bSnowcone\b', r'\bChalk\b', r'\bSneeze\b',
    r'\bBlizzard\b', r'\bCream\b', r'\bShabu\b', r'\bTootie\b',
    r'\bRocket Fuel\b', r'\bSugar\b', r'\bSnuff\b', r'\bGum\b',
    r'\bFast\b', r'\bCrystals\b', r'\bAngel Dust\b', r'\bWet\b',
    r'\bSherm\b', r'\bEmbalming Fluid\b', r'\bBoat\b', r'\bZombie\b',
    r'\bPeace Pills\b', r'\bLemonade\b', r'\bWack\b', r'\bSqueeze\b',
    r'\bBlack Magic\b', r'\bBlack Dust\b', r'\bDip\b', r'\bAmp\b',
    r'\bCrank\b', r'\bIce\b', r'\bCrystal\b', r'\bMeth\b', r'\bGlass\b',
    r'\bTina\b', r'\bTweak\b', r'\bCrystal Meth\b', r'\bT\b', r'\bShards\b',
    r'\bWhizz\b', r'\bChalk\b', r'\bPookie\b', r'\bCristy\b',
    r'\bNo Doze\b', r'\bGo\b', r'\bZip\b', r'\bGak\b', r'\bG\b',
    r'\bBatu\b', r'\bDirt\b', r'\bHawaiian Salt\b', r'\bRedneck Cocaine\b',
    r'\bFire\b', r'\bWater\b', r'\bBling\b', r'\bBurn\b', r'\bLove Boat\b',
    r'\bRocket Fuel\b', r'\bToot\b', r'\bCross Tops\b', r'\bBennies\b',
    r'\bBlack Beauties\b', r'\bDexies\b', r'\bHearts\b', r'\bSpeed\b',
    r'\bUppers\b', r'\bWake Ups\b', r'\bBumblebees\b', r'\bTruck Drivers\b',
    r'\bBats\b', r'\bBlues\b', r'\bCrystal\b', r'\bDice\b', r'\bGreenies\b',
    r'\bJellies\b', r'\bWhite Cross\b', r'\bDexy\b', r'\bDiet Pills\b',
    r'\bWest Coast Turnarounds\b', r'\bPep Pills\b', r'\bCrosstops\b',
    r'\bBees\b', r'\bSparks\b', r'\bPoppers\b', r'\bRush\b', r'\bSnappers\b',
    r'\bBold\b', r'\bLocker Room\b', r'\bRave\b', r'\bHard Candy\b',
    r'\bManhattan Special\b', r'\bOral\b', r'\bEgg\b', r'\bChocolate Chip\b',
    r'\bBrown Sugar\b', r'\bH\b', r'\bJunk\b', r'\bSmack\b', r'\bHorse\b',
    r'\bDope\b', r'\bTar\b', r'\bChina White\b', r'\bBlack Tar\b',
    r'\bMexican Mud\b', r'\bHeron\b', r'\bChiva\b', r'\bBoy\b', r'\bMud\b',
    r'\bSkag\b', r'\bDragon\b', r'\bHard Stuff\b', r'\bBrown\b', r'\bUncle\b',
    r'\bAntifreeze\b', r'\bSoda\b', r'\bKiller\b', r'\bSchoolboy\b',
    r'\bLunch Money\b', r'\bDown\b', r'\bDope\b', r'\bBig H\b',
    r'\bCapital H\b', r'\bMexican Brown\b', r'\bThunder\b', r'\bBag\b',
    r'\bButton\b', r'\bBundle\b', r'\bGoods\b', r'\bMurder One\b',
    r'\bPig\b', r'\bPoint\b', r'\bSpeedball\b', r'\bWhizbang\b',
    r'\bMartinis\b', r'\bYellow Bags\b', r'\bDiesel\b', r'\bScag\b',
    r'\bMud\b', r'\bWhite Horse\b', r'\bCoffin Juice\b', r'\bMexican Brown\b',
    r'\bStuff\b', r'\bRopes\b', r'\bBoy\b', r'\bTrains\b', r'\bParachute\b',
    r'\bPanic\b', r'\bCaptain\b', r'\bBeast\b', r'\bBob Hope\b',
    r'\bBig Ben\b', r'\bSnort\b', r'\bSniff\b', r'\bBust\b', r'\bChip\b',
    r'\bClimb\b', r'\bCootie\b', r'\bDiesel Train\b', r'\bHard\b',
    r'\bLady\b', r'\bMexican\b', r'\bChina\b', r'\bBoots\b', r'\bJolly\b',
    r'\bMud Pie\b', r'\bPeach Pit\b', r'\bCoke Mule\b', r'\bPowder Train\b',
    r'\bBrown Bag Special\b', r'\bHitter\b', r'\bBouncer\b', r'\bCrew\b',
    r'\bLiner\b', r'\bCrystal Meth\b', r'\bTina\b', r'\bTweak\b',
    r'\bCrank\b', r'\bGlass\b', r'\bG\b', r'\bGo Fast\b', r'\bMeth\b',
    r'\bPookie\b', r'\bHot Rail\b', r'\bLemon Drop\b', r'\bWhite Cross\b',
    r'\bIce\b', r'\bRock\b', r'\bYaba\b', r'\bChalk\b', r'\bQuartz\b',
    r'\bFire\b', r'\bSpeed\b', r'\bClear\b', r'\bWhiz\b', r'\bDope\b',
    r'\bShabu\b', r'\bCristy\b', r'\bBlack Beauties\b', r'\bBennies\b',
    r'\bDexies\b', r'\bUppers\b', r'\bPep Pills\b', r'\bCross Tops\b',
    r'\bBumblebees\b', r'\bJelly Beans\b', r'\bHearts\b', r'\bMini Thins\b',
    r'\bWhite Cross\b', r'\bWhite Lightning\b', r'\bCheerios\b',
    r'\bBats\b', r'\bPhennies\b', r'\bPoppers\b', r'\bRush\b',
    r'\bLocker Room\b', r'\bBolt\b', r'\bHard\b', r'\bRed\b', r'\bAmph\b',
    r'\bBean\b', r'\bGoop\b', r'\bPopcorn\b', r'\bToothpaste\b',
    r'\bNail Polish Remover\b', r'\bLemon\b', r'\bRocket Fuel\b',
    r'\bSuper Cool\b', r'\bSmileys\b', r'\bSilver\b', r'\bIce Cubes\b',
    r'\bPigeon\b', r'\bBitty Bits\b', r'\bLove Boat\b', r'\bDew\b',
    r'\bFrench Fries\b', r'\bParachutes\b', r'\bAmp\b', r'\bRed Ball\b',
    r'\bRed Cross\b', r'\bSugar\b', r'\bHot Seat\b', r'\bDancers\b',
    r'\bRush\b', r'\bVapor\b', r'\bSage\b', r'\bBuddha\b', r'\bSativa\b',
    r'\bGanja\b', r'\bBud\b', r'\bChronic\b', r'\bMary Jane\b',
    r'\bWeed\b', r'\bDope\b', r'\bPot\b', r'\bGrass\b', r'\bHash\b',
    r'\bHemp\b', r'\bBong\b', r'\bDime\b', r'\bJolly Green Giant\b',
    r'\bZig Zag\b', r'\bDabber\b', r'\bPuff\b', r'\bHit\b',
    r'\bMunchies\b', r'\bCheeba\b', r'\bChronic\b', r'\bSmoke\b',
    r'\bJoint\b', r'\bBlunt\b', r'\bStash\b', r'\bGreen\b', r'\bSkunk\b',
    r'\bTree\b', r'\bCannabis\b', r'\bGanja\b', r'\bMary Jane\b',
    r'\bKind\b', r'\b420\b', r'\bHerb\b', r'\bKush\b', r'\bGrass\b',
    r'\bDoobie\b', r'\bRoach\b', r'\bKief\b', r'\bDab\b', r'\bFuzzy\b',
    r'\bBuds\b', r'\bJoint\b', r'\bWeed\b', r'\bMary Jane\b',
    r'\bSativa\b', r'\bIndica\b', r'\bHash\b', r'\bFlower\b', r'\bSticky\b',
    r'\bNug\b', r'\bBaked\b', r'\bChronic\b', r'\bGanja\b',
    r'\bSmoke\b', r'\bPuff\b', r'\bBlaze\b', r'\bToke\b', r'\bDab\b',
    r'\bBowl\b', r'\bWhiff\b', r'\bToke\b', r'\bFlame\b', r'\bMellow\b',
    r'\bPuff Puff Pass\b', r'\bBlunt\b', r'\bCough\b', r'\bChill\b',
    r'\bDrip\b', r'\bLight Up\b', r'\bToker\b', r'\bHigh\b', r'\bLifted\b',
    r'\bStoned\b', r'\bChronic\b', r'\bGreenery\b', r'\bFlower Power\b',
    r'\bJoint Rolling\b', r'\bBud\b', r'\bBong\b', r'\bChillum\b',
    r'\bHit\b', r'\bJoint\b', r'\bBlunt\b', r'\bPuff\b', r'\bSmoke\b',
    r'\bBowl\b', r'\bVape\b', r'\bClouds\b', r'\bDabs\b', r'\bConcentrates\b',
    r'\bInfused\b', r'\bExtracts\b', r'\bBongs\b', r'\bWeed\b',
    r'\bPots\b', r'\bGanja\b', r'\bGreenery\b', r'\bCronic\b',
    r'\bBuds\b', r'\bDabs\b', r'\bPuff\b', r'\bRoach\b', r'\bJoint\b',
    r'\bBlaze\b', r'\bChronic\b', r'\bBud\b', r'\bGreen\b', r'\bGanja\b',
    r'\bTree\b', r'\bDope\b', r'\bPot\b', r'\bGrass\b', r'\bHash\b',
    r'\bWeed\b', r'\bToke\b', r'\bJoint\b', r'\bBong\b', r'\bStash\b',
    r'\bMunchies\b', r'\bCannabis\b', r'\bKush\b', r'\bSticky\b',
    r'\bNug\b', r'\bMary Jane\b', r'\bHigh\b', r'\bStoned\b',
    r'\bLifted\b', r'\bSmoke\b', r'\bClouds\b', r'\bDabs\b', r'\bConcentrates\b',
    r'\bInfused\b', r'\bExtracts\b', r'\bBongs\b', r'\bDab\b',
    r'\bWeed\b', r'\bGanja\b', r'\bGreenery\b', r'\bChronic\b',
    r'\bBuds\b', r'\bHit\b', r'\bBlaze\b', r'\bLight Up\b', r'\bToker\b',
    r'\bJoint\b', r'\bBlunt\b', r'\bPuff\b', r'\bSmoke\b', r'\bVape\b',
    r'\bWhiff\b', r'\bDab\b', r'\bPuff Puff Pass\b', r'\bToke\b',
    r'\bChill\b', r'\bDrip\b', r'\bLight Up\b', r'\bLifted\b',
    r'\bStoned\b', r'\bGreen\b', r'\bBud\b', r'\bChronic\b',
    r'\bGanja\b', r'\bSmoke\b', r'\bBong\b', r'\bJoint\b', r'\bBlunt\b',
    r'\bPuff\b', r'\bHit\b', r'\bStash\b', r'\bWeed\b', r'\bDope\b',
    r'\bPot\b', r'\bGrass\b', r'\bHash\b', r'\bWeed\b', r'\bPots\b',
    r'\bSticky\b', r'\bNug\b', r'\bChronic\b', r'\bGreenery\b',
    r'\bJoint\b', r'\bBlunt\b', r'\bPuff\b', r'\bSmoke\b', r'\bVape\b',
    r'\bWhiff\b', r'\bDabs\b', r'\bConcentrates\b', r'\bInfused\b',
    r'\bExtracts\b', r'\bBongs\b', r'\bHit\b', r'\bBlaze\b', r'\bLight Up\b',
    r'\bToker\b',r'\bmarijuana\b',
    r"\bAmy\b", r"\bAmps\b", r"\bBam\b", r"\bB-Bombs\b", r"\bBeans\b", r"\bBennies\b", r"\bBenz\b", 
    r"\bBlack and Whites\b", r"\bBlack Beauties\b", r"\bBlack Birds\b", r"\bBlack Bombers\b", 
    r"\bBlack Mollies\b", r"\bBlacks\b", r"\bBlue Boys\b", r"\bBombita\b", r"\bBrain Ticklers\b", 
    r"\bBrownies\b", r"\bBumblebees\b", r"\bCartwheels\b", r"\bChalk\b", r"\bChicken Powder\b", 
    r"\bChochos\b", r"\bChristina\b", r"\bChunk\b", r"\bCo-Pilot\b", r"\bCoasts to Coasts\b", 
    r"\bCrisscross\b", r"\bCross Roads\b", r"\bCross Tops\b", r"\bDebs\b", r"\bDexies\b", 
    r"\bDiablos\b", r"\bDiamonds\b", r"\bDiet Pills\b", r"\bDolls\b", r"\bDominoes\b", 
    r"\bDouble Cross\b", r"\bDrivers\b", r"\bFives\b", r"\bFootballs\b", r"\bFrench Blues\b", 
    r"\bGoofballs\b", r"\bGreenies\b", r"\bHead Drugs\b", r"\bHearts\b", r"\bHorse Heads\b", 
    r"\bIn-Between\b", r"\bJelly Babies\b", r"\bJelly Beans\b", r"\bJolly Beans\b", 
    r"\bJugs\b", r"\bLeapers\b", r"\bLid Poppers\b", r"\bLightening\b", r"\bLittle Bombs\b", 
    r"\bMarathons\b", r"\bMini Beans\b", r"\bMini Bennies\b", r"\bMorning Shot\b", 
    r"\bNuggets\b", r"\bOranges\b", r"\bPastillas\b", r"\bPeaches\b", r"\bPep Pills\b", 
    r"\bPink Hearts\b", r"\bPixies\b", r"\bPollutants\b", r"\bPurple Hearts\b", 
    r"\bRhythm\b", r"\bRippers\b", r"\bRoad Dope\b", r"\bRoses\b", r"\bRueda\b", 
    r"\bSnaps\b", r"\bSnow Pallets\b", r"\bSparkle Plenty\b", r"\bSparklers\b", 
    r"\bSpeed\b", r"\bSplash\b", r"\bSweeties\b", r"\bSweets\b", r"\bTens\b", 
    r"\bThrusters\b", r"\bTR-6s\b", r"\bTruck Drivers\b", r"\bTurnabouts\b", 
    r"\bUppers\b", r"\bWake Ups\b", r"\bWest Coast Turnarounds\b", r"\bWheels\b", 
    r"\bWhiffle Dust\b", r"\bWhite Crosses\b", r"\bWhites\b", r"\bZoomers\b",
    r"\b777\b", r"\bA-1\b", r"\bAll-American Drug\b", r"\bAngel Powder\b", r"\bAngie\b", 
    r"\bAnimals\b", r"\bAudi\b", r"\bAunt Nora\b", r"\bAzucar\b", r"\bBaby Powder\b", 
    r"\bBarrato\b", r"\bBasuco\b", r"\bBazooka\b", r"\bBeach\b", r"\bBelushi\b", 
    r"\bBernie’s Flakes\b", r"\bBernie’s Gold Dust\b", r"\bBig Bloke\b", r"\bBig C\b", 
    r"\bBig Flake\b", r"\bBig Rush\b", r"\bBillie Hoke\b", r"\bBird\b", r"\bBirdie Powder\b", 
    r"\bBlanca Nieves\b", r"\bBlanco\b", r"\bBlast\b", r"\bBlizzard\b", r"\bBlonde\b", 
    r"\bBlocks\b", r"\bBlow\b", r"\bBMW\b", r"\bBobo\b", r"\bBolitas\b", 
    r"\bBolivian Marching Powder\b", r"\bBombita\b", r"\bBouncing Powder\b", r"\bBrisa\b", 
    r"\bC-Dust\b", r"\bCaca\b", r"\bCadillac\b", r"\bCalifornia Pancakes\b", r"\bCalves\b", 
    r"\bCandy\b", r"\bCar\b", r"\bCarney\b", r"\bCarrie Nation\b", r"\bCars\b", 
    r"\bCase\b", r"\bCebolla\b", r"\bCecil\b", r"\bCement\b", r"\bCharlie\b", 
    r"\bChevy\b", r"\bCheyenne\b", r"\bChinos\b", r"\bChiva\b", r"\bClear Kind\b", 
    r"\bClear Tires\b", r"\bCoca\b", r"\bCoca-Cola\b", r"\bCocazo\b", r"\bCoconut\b", 
    r"\bCoke\b", r"\bCola\b", r"\bColorado\b", r"\bConnie\b", r"\bCookie\b", 
    r"\bCrow\b", r"\bCrusty Treats\b", r"\bCuadro\b", r"\bDeath Valley\b", 
    r"\bDesigner Jeans\b", r"\bDevil’s Dandruff\b", r"\bDiente\b", r"\bDienton\b", 
    r"\bDona Blanca\b", r"\bDouble Bubble\b", r"\bDove\b", r"\bDream\b", r"\bDulces\b", 
    r"\bDuracell\b", r"\bDust\b", r"\bEscama\b", r"\bEscorpino\b", r"\bFalopa\b", 
    r"\bFish\b", r"\bFlake\b", r"\bFlea Market Jeans\b", r"\bFlorida Snow\b", 
    r"\bFlour\b", r"\bFood\b", r"\bFoolish Powder\b", r"\bFox\b", r"\bFreeze\b", 
    r"\bFriskie Powder\b", r"\bFrula\b", r"\bGabacho\b", r"\bGalaxy\b", r"\bGallos\b", 
    r"\bGato\b", r"\bGift of the Sun\b", r"\bGin\b", r"\bGirl\b", r"\bGirlfriend\b", 
    r"\bGlad Stuff\b", r"\bGold Dust\b", r"\bGreen Gold\b", r"\bGringa\b", 
    r"\bGrout\b", r"\bGueros\b", r"\bGuitar\b", r"\bHamburger\b", r"\bHappy Dust\b", 
    r"\bHappy Powder\b", r"\bHappy Trails\b", r"\bHeaven\b", r"\bHeaven Dust\b", 
    r"\bHenry VIII\b", r"\bHooter\b", r"\bHundai\b", r"\bHunter\b", r"\bIcing\b", 
    r"\bInca Message\b", r"\bIzzy\b", r"\bJam\b", r"\bJeep\b", r"\bJelly\b", 
    r"\bJohn Deere\b", r"\bJoy Flakes\b", r"\bJoy Powder\b", r"\bJunk\b", 
    r"\bKing’s Habit\b", r"\bKordell\b", r"\bLady\b", r"\bLady Snow\b", 
    r"\bLate Night\b", r"\bLavada\b", r"\bLeaf\b", r"\bLine\b", r"\bLoaf\b", 
    r"\bLove Affair\b", r"\bMaca Flour\b", r"\bMama Coca\b", r"\bMandango\b", 
    r"\bMaradona\b", r"\bMayo\b", r"\bMelcocha\b", r"\bMercedes\b", r"\bMilk\b", 
    r"\bMilonga\b", r"\bMojo\b", r"\bMona Lisa\b", r"\bMosquitos\b", 
    r"\bMovie Star Drug\b", r"\bMujer\b", r"\bNapkin\b", r"\bNieve\b", 
    r"\bNiña\b", r"\bNose Candy\b", r"\bNose Powder\b", r"\bOld Lady\b", 
    r"\bOyster Stew\b", r"\bPaint\b", r"\bPaloma\b", r"\bPalomos\b", 
    r"\bPantalones\b", r"\bPapas\b", r"\bParadise\b", r"\bParadise White\b", 
    r"\bParrot\b", r"\bPearl\b", r"\bPedrito\b", r"\bPerico\b", r"\bPeruvian\b", 
    r"\bPeruvian Flake\b", r"\bPeruvian Lady\b", r"\bPescado\b", r"\bPez\b", 
    r"\bPillow\b", r"\bPimp\b", r"\bPollo\b", r"\bPolvo\b", r"\bPowder\b", 
    r"\bPowder Diamonds\b", r"\bPuritain\b", r"\bQueso Blanco\b", 
    r"\bRacehorse Charlie\b", r"\bRambo\b", r"\bRefresco\b",
    r"\bRefrescas\b", r"\bReindeer Dust\b", r"\bRims\b", r"\bRocky Mountain\b", 
    r"\bRolex\b", r"\bRooster\b", r"\bScale\b", r"\bSchmeck\b", r"\bSchoolboy\b", 
    r"\bScorpion\b", r"\bScottie\b", r"\bSeed\b", r"\bSerpico\b", r"\bSierra\b", 
    r"\bShirt\b", r"\bSki Equipment\b", r"\bSleigh Ride\b", r"\bSnow\b", 
    r"\bSnow Bird\b", r"\bSnow Cone\b", r"\bSnow White\b", r"\bSnowball\b", 
    r"\bSnowflake\b", r"\bSociety High\b", r"\bSoda\b", r"\bSoditas\b", 
    r"\bSoft\b", r"\bSpace\b", r"\bSpeedball\b", r"\bStardust\b", 
    r"\bStar Spangled Powder\b", r"\bStudio Fuel\b", r"\bSuave\b", 
    r"\bSugar\b", r"\bSuperman\b", r"\bSweet Stuff\b", r"\bTalco\b", 
    r"\bTalquito\b", r"\bTamales\b", r"\bTaxi\b", r"\bTecate\b", 
    r"\bTeenager\b", r"\bTeeth\b", r"\bTequila\b", r"\bThunder\b", 
    r"\bTire\b", r"\bTonto\b", r"\bToot\b", r"\bTortes\b", 
    r"\bToyota\b", r"\bT-Shirts\b", r"\bTurkey\b", r"\bTutti-Frutti\b", 
    r"\bVaquita\b", r"\bWash\b", r"\bWet\b", r"\bWhack\b", 
    r"\bWhite\b", r"\bWhite Bitch\b", r"\bWhite Cross\b", 
    r"\bWhite Girl\b", r"\bWhite Goat\b", r"\bWhite Horse\b", 
    r"\bWhite Lady\b", r"\bWhite Mercedes Benz\b", r"\bWhite Mosquito\b", 
    r"\bWhite Paint\b", r"\bWhite Powder\b", r"\bWhite Root\b", 
    r"\bWhite Shirt\b", r"\bWhite T\b", r"\bWhitey\b", 
    r"\bWhiz Bang\b", r"\bWings\b", r"\bWooly\b", r"\bWork\b", 
    r"\bYayo\b", r"\bYeyo\b", r"\bYoda\b", r"\bZip\b",
    r"\b51s\b", r"\b151s\b", r"\b501s\b", r"\bApple Jack\b", r"\bBaby T\b", 
    r"\bBase\b", r"\bBaseball\b", r"\bBazooka\b", r"\bBeam Me Up\b", 
    r"\bBeautiful Boulders\b", r"\bBeemer\b", r"\bBill Blass\b", r"\bBings\b", 
    r"\bBJ\b", r"\bBlack Rock\b", r"\bBlowcaine\b", r"\bBlowout\b", r"\bBlue\b", 
    r"\bBobo\b", r"\bBolo\b", r"\bBomb\b", r"\bBone Crusher\b", r"\bBone\b", 
    r"\bBoo-Boo\b", r"\bBoulder\b", r"\bBoy\b", r"\bBreakfast of Champions\b", 
    r"\bBubble Gum\b", r"\bBullion\b", r"\bBump\b", r"\bCandy\b", 
    r"\bCaps\b", r"\bCasper the Ghost\b", r"\bCaviar\b", r"\bCD\b", 
    r"\bCheap Basing\b", r"\bChewies\b", r"\bChingy\b", r"\bClicker\b", 
    r"\bClimax\b", r"\bCloud\b", r"\bCloud Nine\b", r"\bCookies\b", r"\bCrib\b", 
    r"\bCrunch & Munch\b", r"\bDevil\b", r"\bDevil Smoke\b", r"\bDice\b", 
    r"\bDime Special\b", r"\bDirty Basing\b", r"\bDirty Fentanyl\b", 
    r"\bDouble Yoke\b", r"\bDurin\b", r"\bEastside Player\b", r"\bEgg\b", 
    r"\bEye Opener\b", r"\bFamous Dimes\b", r"\bFat Bags\b", r"\bFifty-One\b", 
    r"\bFish Scales\b", r"\bFreebase\b", r"\bFrench Fries\b", r"\bGarbage Rock\b", 
    r"\bGeek\b", r"\bGlo\b", r"\bGold\b", r"\bGolf Ball\b", r"\bGravel\b", 
    r"\bGreat White Hope\b", r"\bGrit\b", r"\bGroceries\b", r"\bHail\b", 
    r"\bHamburger Helper\b", r"\bHard\b", r"\bHotcakes\b", r"\bHubba\b", 
    r"\bIce\b", r"\bIce Cubes\b", r"\bIssues\b", r"\bJelly Beans\b", 
    r"\bJohnson\b", r"\bKangaroo\b", r"\bKokoma\b", r"\bKryptonite\b", 
    r"\bLove\b", r"\bMixed Jive\b", r"\bMoon Rock\b", r"\bNickel\b", 
    r"\bNuggets\b", r"\bOne-Fifty-One\b", r"\bPaste\b", r"\bPebbles\b", 
    r"\bPee Wee\b", r"\bPiedras\b", r"\bPile\b", r"\bPony\b", r"\bPrimo\b", 
    r"\bQuarters\b", r"\bRaw\b", r"\bReady Rock\b", r"\bRed Caps\b", 
    r"\bRIP\b", r"\bRoca\b", r"\bRock\b", r"\bRock Attack\b", 
    r"\bRocks of Hell\b", r"\bRocky III\b", r"\bRooster\b", r"\bRox\b", 
    r"\bRoxanne\b", r"\bRoz\b", r"\bSchoolcraft\b", r"\bScotty\b", 
    r"\bScramble\b", r"\bScruples\b", r"\bSeven-Up\b", r"\bSherms\b", 
    r"\bSight Ball\b", r"\bSlab\b", r"\bSleet\b", r"\bSmoke\b", 
    r"\bSpeed Boat\b", r"\bSquare Time Bomb\b", r"\bStone\b", 
    r"\bSugar Block\b", r"\bTakeover\b", r"\bTeeth\b", r"\bTension\b", 
    r"\bTissue\b", r"\bTop Gun\b", r"\bTroop\b", r"\bUltimate\b", 
    r"\bUzi\b", r"\bWave\b", r"\bWhite Ball\b", r"\bWhite Ghost\b", 
    r"\bWhite Sugar\b", r"\bWhite Tornado\b", r"\bWrecking Crew\b", 
    r"\bYahoo\b", r"\bYale\b", r"\bYimyom\b",
    r"\bApache\b", r"\bBirria\b", r"\bButter\b", r"\bChina Girl\b", r"\bChina Town\b", 
    r"\bChina White\b", r"\bChinese\b", r"\bChinese Food\b", r"\bCrazy\b", 
    r"\bCrazy One\b", r"\bDance Fever\b", r"\bDragon\b", r"\bDragon’s Breath\b", 
    r"\bFacebook\b", r"\bFent\b", r"\bFenty\b", r"\bFire\b", r"\bFriend\b", 
    r"\bGirl\b", r"\bGoodfella\b", r"\bGreat Bear\b", r"\bHe-Man\b", r"\bJackpot\b", 
    r"\bKing Ivory\b", r"\bLollipop\b", r"\bMurder 8\b", r"\bPoison\b", 
    r"\bShoes\b", r"\bTango & Cash\b", r"\bToe Tag Dope\b", r"\bWhite Girl\b",
    r"\bApache\b", r"\bBirria\b", r"\bButter\b", r"\bChina Girl\b", r"\bChina Town\b", 
    r"\bChina White\b", r"\bChinese\b", r"\bChinese Food\b", r"\bCrazy\b", 
    r"\bCrazy One\b", r"\bDance Fever\b", r"\bDragon\b", r"\bDragon’s Breath\b", 
    r"\bFacebook\b", r"\bFent\b", r"\bFenty\b", r"\bFire\b", r"\bFriend\b", 
    r"\bGirl\b", r"\bGoodfella\b", r"\bGreat Bear\b", r"\bHe-Man\b", r"\bJackpot\b", 
    r"\bKing Ivory\b", r"\bLollipop\b", r"\bMurder 8\b", r"\bPoison\b", 
    r"\bShoes\b", r"\bTango & Cash\b", r"\bToe Tag Dope\b", r"\bWhite Girl\b",
    r"\bA-Bomb\b", r"\bAchivia\b", r"\bAdormidera\b", r"\bAntifreeze\b", r"\bAunt Hazel\b", r"\bAvocado\b", 
    r"\bAzucar\b", r"\bBad Seed\b", r"\bBallot\b", r"\bBasketball\b", r"\bBasura\b", r"\bBeast\b", 
    r"\bBeyonce\b", r"\bBig Bag\b", r"\bBig H\b", r"\bBig Harry\b", r"\bBird\b", r"\bBirdie Powder\b", 
    r"\bBlack\b", r"\bBlack Bitch\b", r"\bBlack Goat\b", r"\bBlack Olives\b", r"\bBlack Paint\b", 
    r"\bBlack Pearl\b", r"\bBlack Sheep\b", r"\bBlack Tar\b", r"\bBlanco\b", r"\bBlue\b", r"\bBlow Dope\b", 
    r"\bBlue Hero\b", r"\bBombita\b", r"\bBombs Away\b", r"\bBonita\b", r"\bBoy\b", r"\bBozo\b", 
    r"\bBrea Negra\b", r"\bBrick Gum\b", r"\bBrown\b", r"\bBrown Crystal\b", r"\bBrown Rhine\b", 
    r"\bBrown Sugar\b", r"\bBubble Gum\b", r"\bBurrito\b", r"\bCaballo\b", r"\bCaballo Negro\b", 
    r"\bCaca\b", r"\bCafé\b", r"\bCapital H\b", r"\bCarga\b", r"\bCaro\b", r"\bCement\b", r"\bChapopote\b", 
    r"\bCharlie\b", r"\bCharlie Horse\b", r"\bCheese\b", r"\bChicle\b", r"\bChiclosa\b", r"\bChina\b", 
    r"\bChina Cat\b", r"\bChina White\b", r"\bChinese Food\b", r"\bChinese Red\b", r"\bChip\b", 
    r"\bChiva\b", r"\bChiva Blanca\b", r"\bChivones\b", r"\bChocolate\b", r"\bChocolate Balls\b", 
    r"\bChoko\b", r"\bChorizo\b", r"\bChutazo\b", r"\bCoco\b", r"\bCoffee\b", r"\bComida\b", r"\bCrown Crap\b", 
    r"\bCurley Hair\b", r"\bDark\b", r"\bDark Girl\b", r"\bDead on Arrival\b", r"\bDOA\b", r"\bDiesel\b", 
    r"\bDirt\b", r"\bDog Food\b", r"\bDoggie\b", r"\bDoojee\b", r"\bDope\b", r"\bDorado\b", r"\bDown\b", 
    r"\bDowntown\b", r"\bDreck\b", r"\bDynamite\b", r"\bDyno\b", r"\bEl Diablo\b", r"\bEngines\b", 
    r"\bFairy Dust\b", r"\bFlea Powder\b", r"\bFoolish Powder\b", r"\bGalloping Horse\b", r"\bGamot\b", 
    r"\bGato\b", r"\bGeorge\b",
    r"\b357s\b", r"\bBananas\b", r"\bDro\b", r"\bFluff\b", r"\bHydro\b", r"\bTabs\b", r"\bNorco\b", r"\bVics\b", 
    r"\bVikes\b", r"\bWatsons\b", r"\bBlind Squid\b", r"\bCat Valium\b", r"\bGreen\b", r"\bHoney Oil\b", r"\bJet\b", 
    r"\bK\b", r"\bKeller\b", r"\bKelly’s Day\b", r"\bK-Hold\b", r"\bK-Ways\b", r"\bSpecial K\b", r"\bSuper Acid\b",
    r"\bVitamin K\b", r"\bK\b", r"\bK-Pin\b", r"\bPin\b", r"\bSuper Valium\b", r"\bAceite\b", r"\bAcid\b", 
    r"\bAcido\b", r"\bAlice\b", r"\bAngels in a Sky\b", r"\bAnimal\b", r"\bBackbreaker\b", r"\bBarrel\b", 
    r"\bBart Simpson\b", r"\bBattery Acid\b", r"\bBeast\b", r"\bBig D\b", r"\bBlack Acid\b", r"\bBlack Star\b", 
    r"\bBlack Sunshine\b", r"\bBlack Tabs\b", r"\bBlotter Acid\b", r"\bBlotter Cube\b", r"\bBlue Acid\b", 
    r"\bBlue Barrel\b", r"\bBlue Chair\b", r"\bBlue Cheer\b", r"\bBlue Heaven\b", r"\bBlue Microdots\b", 
    r"\bBlue Mist\b", r"\bBlue Moon\b", r"\bBlue Sky\b", r"\bBlue Star\b", r"\bBlue Tabs\b", r"\bBrown Bomber\b", 
    r"\bBrown Dots\b", r"\bCalifornia Sunshine\b", r"\bCherry Dome\b", r"\bChief\b", r"\bChinese Dragons\b", 
    r"\bCoffee\b", r"\bConductor\b", r"\bContact Lens\b", r"\bCrackers\b", r"\bCrystal Tea\b", r"\bCupcakes\b", 
    r"\bDental Floss\b", r"\bDinosaurs\b", r"\bDomes\b", r"\bDots\b", r"\bDouble Dome\b", r"\bEl Cid\b", 
    r"\bElectric Kool Aid\b", r"\bEllis Day\b", r"\bFields\b", r"\bFlash\b", r"\bFlat Blues\b", r"\bGhost\b", 
    r"\bGolden Dragon\b", r"\bGolf Balls\b", r"\bGoofy\b", r"\bGota\b", r"\bGrape Parfait\b", r"\bGreen Wedge\b", 
    r"\bGrey Shields\b", r"\bHats\b", r"\bHawaiian Sunshine\b", r"\bHawk\b", r"\bHaze\b", r"\bHeadlights\b", 
    r"\bHeavenly Blue\b", r"\bHits\b", r"\bInstant Zen\b", r"\bJesus Christ Acid\b", r"\bKaleidoscope\b", 
    r"\bLeary\b", r"\bLens\b", r"\bLime Acid\b", r"\bLive, Spit & Die\b", r"\bLucy in the Sky with Diamonds\b", 
    r"\bMellow Yellow\b", r"\bMica\b", r"\bMicrodot\b", r"\bMighty Quinn\b", r"\bMind Detergent\b", 
    r"\bMother of God\b", r"\bNewspapers\b", r"\bOrange Barrels\b", r"\bOrange Cubes\b", r"\bOrange Haze\b", 
    r"\bOrange Micros\b", r"\bOrange Wedges\b", r"\bOwsley\b", r"\bPaper Acid\b", r"\bPearly Gates\b", 
    r"\bPellets\b", r"\bPhoenix\b", r"\bPink Blotters\b", r"\bPink Panthers\b", r"\bPink Robots\b", 
    r"\bPink Wedges\b", r"\bPink Witches\b", r"\bPizza\b", r"\bPotato\b", r"\bPure Love\b", r"\bPurple Barrels\b", 
    r"\bPurple Haze\b", r"\bPurple Hearts\b", r"\bPurple Flats\b", r"\bRecycle\b", r"\bRoyal Blues\b", 
    r"\bRussian Sickles\b", r"\bSacrament\b", r"\bSandoz\b", r"\bSmears\b", r"\bSquare Dancing Tickets\b", 
    r"\bStrawberry Fields\b", r"\bSugar Cubes\b", r"\bSugar Lumps\b", r"\bSunshine\b", r"\bTabs\b", 
    r"\bTacatosa\b", r"\bTail Lights\b", r"\bTeddy Bears\b", r"\bTicket\b", r"\bUncle Sid\b", r"\bValley Dolls\b", 
    r"\bVodka Acid\b", r"\bWedding Bells\b", r"\bWedge\b", r"\bWhite Dust\b", r"\bWhite Fluff\b", 
    r"\bWhite Lightening\b", r"\bWhite Owsley\b", r"\bWindow Glass\b", r"\bWindow Pane\b", r"\bYellow Dimples\b", 
    r"\bYellow Sunshine\b", r"\bZen\b",
    r"\b246\b", r"\bBHO\b", r"\bBadder\b", r"\bBudder\b", r"\bButter\b", r"\bDabs\b", r"\bEar Wax\b", r"\bErrl\b",
    r"\bHoney Oil\b", r"\bSAP\b", r"\bShatter\b", r"\bWax\b", r"\bAdam\b", r"\bBaby Slits\b", r"\bBean\b",
    r"\bBlue Kisses\b", r"\bBooty Juice\b", r"\bCandy\b", r"\bChocolate Chips\b", r"\bClarity\b", r"\bDancing Shoes\b",
    r"\bDecadence\b", r"\bDoctor\b", r"\bDomex\b", r"\bE\b", r"\bE-Bomb\b", r"\bEcstasy\b", r"\bEssence\b", 
    r"\bEve\b", r"\bKleenex\b", r"\bLove Doctor\b", r"\bLove Drug\b", r"\bLove Potion #9\b", r"\bLove Trip\b", 
    r"\bMolly\b", r"\bMoon Rock\b", r"\bRoll\b", r"\bRolling\b", r"\bRunning\b", r"\bScooby Snacks\b", r"\bSkittle\b", 
    r"\bSlits\b", r"\bSmartees\b", r"\bSpeed for Lovers\b", r"\bSweets\b", r"\bVitamin E\b", r"\bX\b", r"\bXTC\b", 
    r"\bBig Chief\b", r"\bBlue Caps\b", r"\bButtons\b", r"\bCactus\b", r"\bMedia Luna\b", r"\bMescal\b", 
    r"\bMezcakuba\b", r"\bMoon\b", r"\bSan Pedro\b", r"\bTopi\b", r"\bAccordion\b", r"\bAqua\b", r"\bBatu\b", 
    r"\bBlue\b", r"\bBlue Bell Ice Cream\b", r"\bBeers\b", r"\bBottles\b", r"\bBud Light\b", r"\bBump\b", 
    r"\bCajitas\b", r"\bChalk\b", r"\bChavalones\b", r"\bChicken\b", r"\bChicken Powder\b", r"\bChristine\b", 
    r"\bChristy\b", r"\bClear\b", r"\bClothing Cleaner\b", r"\bColorado Rockies\b", r"\bCrank\b", r"\bCream\b", 
    r"\bCri-Cri\b", r"\bCrink\b", r"\bCrisco\b", r"\bCrypto\b", r"\bCrystal\b", r"\bCuadros\b", r"\bDay\b", 
    r"\bEl Gata Diablo\b", r"\bEvil Sister\b", r"\bEye Glasses\b", r"\bFire\b", r"\bFizz\b", r"\bFlowers\b", 
    r"\bFood\b", r"\bFrio\b", r"\bG-Funk\b", r"\bGifts\b", r"\bGirls\b", r"\bGlass\b", r"\bGo-Fast\b", 
    r"\bGroceries\b", r"\bHard Ones\b", r"\bHare\b", r"\bHawaiian Salt\b", r"\bHielo\b", r"\bHot Ice\b", 
    r"\bIce\b", r"\bIce Cream\b", r"\bJug of Water\b", r"\bL.A. Glass\b", r"\bL.A. Ice\b", r"\bLemons\b", 
    r"\bLemon Drop\b", r"\bLight\b", r"\bLight Beige\b", r"\bLivianas\b", r"\bMadera\b", r"\bMeth\b", 
    r"\bMexican Crack\b", r"\bMexican Crank\b", r"\bMiss Girl\b", r"\bMontura\b", r"\bMotor\b", r"\bMuchacha\b", 
    r"\bNails\b", r"\bOne Pot\b", r"\bPantalones\b", r"\bPeanut Butter Crank\b", r"\bPiñata\b", r"\bPointy Ones\b", 
    r"\bPollito\b", r"\bPopsicle\b", r"\bPurple\b", r"\bRaspado\b", r"\bRims\b", r"\bSalt\b", r"\bShabu\b", 
    r"\bShards\b", r"\bShatter\b", r"\bShaved Ice\b", r"\bShiny Girl\b", r"\bSoap Dope\b", r"\bSoft Ones\b", 
    r"\bSpicy Kind\b", r"\bStove Top\b", r"\bStuff\b", r"\bSuper Ice\b", r"\bTable\b", r"\bTina\b", r"\bTruck\b", 
    r"\bTupperware\b", r"\bVentanas\b", r"\bVidrio\b", r"\bWalking Zombie\b", r"\bWater\b", r"\bWhite\b", 
    r"\bWindows\b", r"\bWitches Teeth\b", r"\bYellow Barn\b", r"\bYellow Kind\b", r"\bZip\b", r"\bAlice\b", 
    r"\bBoomers\b", r"\bButtons\b", r"\bCaps\b", r"\bChampiñones\b", r"\bHongos\b", r"\bMagic\b", r"\bMushies\b", 
    r"\bPizza Toppings\b", r"\bShrooms\b", r"\bTweezes\b", r"\bAuntie\b", r"\bAunt Emma\b", r"\bBig O\b", 
    r"\bBlack\b", r"\bBlack Russian\b", r"\bChandoo\b", r"\bChina\b", r"\bChinese Molasses\b", r"\bChinese Tobacco\b", 
    r"\bChocolate\b", r"\bCruz\b", r"\bDopium\b", r"\bDover’s Powder\b", r"\bDream Gum\b", r"\bDream Stick\b", 
    r"\bDreams\b", r"\bEasing Powder\b", r"\bGod’s Medicine\b", r"\bGoma\b", r"\bGondola\b", r"\bGoric\b", 
    r"\bGreat Tobacco\b", r"\bGum\b", r"\bHocus\b", r"\bHops\b", r"\bIncense\b", r"\bJoy Plant\b", 
    r"\bMidnight Oil\b", r"\bOpio\b", r"\bPen Yan\b", r"\bPin Gon\b", r"\bPin Yen\b", r"\bPox\b", r"\bSkee\b", 
    r"\bToxy\b", r"\bToys\b", r"\bWhen-Shee\b", r"\bZero\b", r"\b30s\b", r"\b40s\b", r"\bBeans\b", 
    r"\bBlues\b", r"\bButtons\b", r"\bGreens\b", r"\bOC\b", r"\bOxy\b", r"\bWhites\b", r"\bAce\b", 
    r"\bAlien Sex Fiend\b", r"\bAmoeba\b", r"\bAngel\b", r"\bAngel Dust\b", r"\bAngel Hair\b", r"\bAngel Mist\b", 
    r"\bAngel Poke\b", r"\bAnimal Tranquilizer\b", r"\bAurora Borealis\b", r"\bBlack Acid\b", r"\bBlack Whack\b", 
    r"\bBlue Madman\b", r"\bBlue Star\b", r"\bBoat\b", r"\bBusy Bee\b", r"\bButt Naked\b", r"\bCadillac\b", 
    r"\bCliffhanger\b", r"\bColumbo\b", r"\bCozmos\b", r"\bCrazy Coke\b", r"\bCrazy Eddie\b", r"\bCucuy\b", 
    r"\bCyclones\b", r"\bDetroit Pink\b", r"\bDipper\b", r"\bDomex\b", r"\bDummy Dust\b", r"\bDust\b", 
    r"\bDust Joint\b", r"\bDust of Angels\b", r"\bElephant\b", r"\bElephant Tranquilizer\b", r"\bEmbalming Fluid\b", 
    r"\bEnergizer\b", r"\bFake STP\b", r"\bFlakes\b", r"\bGoon\b", r"\bGorilla Tab\b", r"\bGorilla Biscuits\b", 
    r"\bGreen Leaves\b", r"\bGreen Tea\b", r"\bHeaven & Hell\b", r"\bHog\b", r"\bHorse Tracks\b", 
    r"\bHorse Tranquilizers\b", r"\bJet Fuel\b", r"\bJuice\b", r"\bKaps\b", r"\bK-Blast\b", r"\bKiller\b", 
    r"\bKools\b", r"\bLeaky Leak\b", r"\bLemon 714\b", r"\bLethal Weapon\b", r"\bLove Boat\b", r"\bMad Dog\b", 
    r"\bMad Man\b", r"\bMagic Dust\b", r"\bMean Green\b", r"\bMint Leaf\b", r"\bMint Weed\b", r"\bMist\b", 
    r"\bMonkey Dust\b", r"\bMonkey Tranquilizer\b", r"\bNew Acid\b", r"\bNew Magic\b", r"\bOrange Crystal\b", 
    r"\bOzone\b", r"\bPaz\b", r"\bPeace Pill\b", r"\bPeep\b", r"\bPeter Pan\b", r"\bPig Killer\b", 
    r"\bPuffy\b", r"\bPurple Rain\b", r"\bRed Devil\b", r"\bRocket Fuel\b", r"\bRupture\b", r"\bScuffle\b", 
    r"\bSheets\b", r"\bSherms\b", r"\bShermstick\b", r"\bSpace\b", r"\bSpores\b", r"\bStardust\b", 
    r"\bSTP\b", r"\bSuper Grass\b", r"\bSuper Kools\b", r"\bSurfer\b", r"\bSynthetic Cocaine\b", r"\bTaking a Cruise\b", 
    r"\bT-Buzz\b", r"\bTic Tac\b", r"\bTish\b", r"\bTrank\b", r"\bVenom\b", r"\bWack\b", r"\bWater\b", 
    r"\bWet\b", r"\bWhite Horizon\b", r"\bWobble Weed\b", r"\bWolf\b", r"\bWorm\b", r"\bYellow Fever\b", 
    r"\bZombie\b", r"\bZoom\b",
    r"\b512s\b", r"\bBananas\b", r"\bBlue\b", r"\bBlueberries\b", r"\bButtons\b", r"\bErcs\b", r"\bGreenies\b",
    r"\bHillbilly Heroin\b", r"\bKickers\b", r"\bM-30s\b", r"\bPercs\b", r"\bRims\b", r"\bTires\b", r"\bWheels\b",
    r"\bBlack Button\b", r"\bBritton\b", r"\bButton\b", r"\bCactus\b", r"\bGreen Button\b", r"\bHalf Moon\b",
    r"\bHikori\b", r"\bHikuli\b", r"\bHyatari\b", r"\bNubs\b", r"\bSeni\b", r"\bShaman\b", r"\bTops\b",
    r"\bAct\b", r"\bDrank\b", r"\bLean\b", r"\bPurple\b", r"\bPurple Drank\b", r"\bSizurup\b", r"\bSizzurp\b", r"\bSyrup\b",
    r"\bKibbles and Bits\b", r"\b4-20\b", r"\bAbyss\b", r"\bAce of Spades\b", r"\bAK-47\b", r"\bAmnesia\b", 
    r"\bAtomic Blast\b", r"\bBig Bang\b", r"\bBlaze\b", r"\bBlack Magic Smoke\b", r"\bBlack Mamba\b", 
    r"\bBlue Cheese\b", r"\bBrain Freeze\b", r"\bBuzz Haze\b", r"\bCherry Bomb\b", r"\bChill\b", r"\bChrome\b", 
    r"\bClockwork Orange\b", r"\bCloud 10\b", r"\bCowboy Kush\b", r"\bCrystal Skull\b", r"\bDead Man\b", 
    r"\bDevil’s Venom\b", r"\bDr. Feel Good\b", r"\bDragon Eye\b", r"\bEarth Blend\b", r"\bExodus\b", 
    r"\bExtreme\b", r"\bFake Bake\b", r"\bFruit Candy Flavors\b", r"\bFunky Buddha\b", r"\bFunky Monkey\b", 
    r"\bG-Force\b", r"\bGI Joe\b", r"\bGreen Dream\b", r"\bGreen Peace\b", r"\bHammer Head\b", r"\bHelix\b", 
    r"\bHipster\b", r"\bHysteria\b", r"\bIce Dragon\b", r"\bJuicy Leaf\b", r"\bJungle Juice\b", r"\bJust Chill\b", 
    r"\bK2\b", r"\bKaos\b", r"\bKarma\b", r"\bKong\b", r"\bKrazy Kandy\b", r"\bKryp2nite\b", r"\bKush\b", 
    r"\bLayer Cake\b", r"\bLimitless\b", r"\bMad Hatter\b", r"\bMile High\b", r"\bMystique\b", r"\bNinja\b", 
    r"\bOdyssey\b", r"\bOMG\b", r"\bPandora’s Box\b", r"\bPhoenix\b", r"\bPineapple Express\b", r"\bPosh\b", 
    r"\bPotpourri\b", r"\bPow\b", r"\bRapture\b", r"\bRed Magic\b", r"\bRewind\b", r"\bScooby Snax\b", 
    r"\bSexy\b", r"\bSky High\b", r"\bSnake Bite\b", r"\bSpice\b", r"\bSpike Diamond\b", r"\bStorm\b", 
    r"\bSweet Leaf\b", r"\bSynthetic Marijuana\b", r"\bTime Traveler\b", r"\bTop Gear\b", r"\bTrain Wreck\b", 
    r"\bUltimate\b", r"\bViper\b", r"\bVoodoo Child\b", r"\bWazabi\b", r"\bWicked\b", r"\bWizard\b", 
    r"\bXtreme\b", r"\bZero Gravity\b", r"\bZombie\b", r"\bBath Salts\b", r"\bBliss\b", r"\bBloom\b", 
    r"\bBlow\b", r"\bBlue Silk\b", r"\bCloud 9\b", r"\bDrone\b", r"\bEnergy-1\b", r"\bExplosion\b", r"\bFlakka\b", 
    r"\bGravel\b", r"\bInsect Repellant\b", r"\bIvory Wave\b", r"\bJewelry Cleaner\b", r"\bLunar Wave\b", 
    r"\bM-Cat\b", r"\bMeow-Meow\b", r"\bOcean Burst\b", r"\bPhone Screen Cleaner\b", r"\bPlant Food\b", 
    r"\bPure Ivory\b", r"\bPurple Wave\b", r"\bRecharge\b", r"\bRed Dove\b", r"\bScarface\b", r"\bSnow Leopard\b", 
    r"\bStardust\b", r"\bVanilla Sky\b", r"\bWhite Dove\b", r"\bWhite Knight\b", r"\bWhite Lightening\b", 
    r"\bWhite Magic\b", r"\bZoom\b", r"\bBars\b", r"\bBicycle Handle Bars\b", r"\bFootballs\b", r"\bHulk\b", 
    r"\bLadders\b", r"\bPlanks\b", r"\bSchool Bus\b", r"\bSticks\b", r"\bXanies\b", r"\bZanbars\b", r"\bZannies\b", 
    r"\bZ-Bars\b"
]







